apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config-volume
data:
  application.yml: |-
    spring:
      application:
        name: capstone
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
          ddl-auto: update
      h2:
        console:
          enabled: true
          path: /h2-console
          settings.trace: true
          settings.web-allow-others: true

    server:
      servlet:
        context-path: /fic
      port: 8888

    h2.database:
      jdbcUrl: jdbc:h2:mem:FICDB
      driverClassName: org.h2.Driver
      username: sa
      password: password
