apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone-service
spec:
  type: ClusterIP
  selector:
    app: capstone-service
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
